{% set name = 'configr' %}
{% set version = '0.3.2.1' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr, rmarkdown
requirements:
  build:
    - r-base
    - r-rcpptoml
    - r-glue
    - r-ini
    - r-jsonlite
    - r-stringr
    - r-yaml
    - r-svunit
    - r-xml

  run:
    - r-base
    - r-rcpptoml
    - r-glue
    - r-ini
    - r-jsonlite
    - r-stringr
    - r-yaml
    - r-svunit
    - r-xml

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('configr')"  # [not win]
    - "\"%R%\" -e \"library('configr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/Miachol/configr
  license: MIT + file LICENSE
  summary: ' Implements the JSON, INI, YAML and TOML parser for R setting and writing of configuration
    file. The functionality of this package is similar to that of package ''config''. '

  license_family: MIT

# The original CRAN metadata for this package was:

# Package: configr
# Type: Package
# Title: An Implementation of Parsing and Writing Configuration File (JSON/INI/YAML/TOML)
# Version: 0.3.2.1
# Authors@R: person("Jianfeng", "Li", email = "lee_jianfeng@sjtu.edu.cn", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-2349-208X"))
# Description:  Implements the JSON, INI, YAML and TOML parser for R setting and writing of configuration file. The functionality of this package is similar to that of package 'config'.
# Depends: R (>= 3.3.0)
# URL: https://github.com/Miachol/configr
# BugReports: https://github.com/Miachol/configr/issues
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# Imports: jsonlite (>= 1.2), ini (>= 0.2), yaml (>= 2.1.3), RcppTOML (>= 0.1.3), stringr (>= 1.2.0), glue
# RoxygenNote: 6.0.1
# Suggests: testthat, knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-02-26 15:21:09 UTC; ljf
# Author: Jianfeng Li [aut, cre] (<https://orcid.org/0000-0003-2349-208X>)
# Maintainer: Jianfeng Li <lee_jianfeng@sjtu.edu.cn>
# Repository: CRAN
# Date/Publication: 2018-02-26 17:17:45 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
