package:
  name: r-rlogging
  version: 0.1

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - bioconductor-biocinstaller
    - r-devtools
    - r-svunit
    - r-xml

  run:
    - r
    - bioconductor-biocinstaller
    - r-devtools
    - r-svunit
    - r-xml
  
test:
  commands:
    - $R -e "library('rlogging')"

about:
  home: https://github.com/mfrasca/r-logging
  license: GPL-2
  summary: R port of the popular log4j logging module







# - r-formatr
# - r-lambda.r
# - r-snow
# - r-futile.logger
# - r-futile.options
# - bioconductor-biocparallel
# pillar
# tibble
# cli
# crayon
# assertthat
# scales
# viridisLite
# RColorBrewer
# munsell
# colorspace
# labeling
# dichromat
# rlang
# utf8
# reshape2
# ggplot2
# gridExtra
